// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomelo-la/go-toolkit/service/aws/s3 (interfaces: Deleter)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/deleter.go -package mock -mock_names Deleter=Deleter . Deleter
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// Deleter is a mock of Deleter interface.
type Deleter struct {
	ctrl     *gomock.Controller
	recorder *DeleterMockRecorder
}

// DeleterMockRecorder is the mock recorder for Deleter.
type DeleterMockRecorder struct {
	mock *Deleter
}

// NewDeleter creates a new mock instance.
func NewDeleter(ctrl *gomock.Controller) *Deleter {
	mock := &Deleter{ctrl: ctrl}
	mock.recorder = &DeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Deleter) EXPECT() *DeleterMockRecorder {
	return m.recorder
}

// DeleteObjects mocks base method.
func (m *Deleter) DeleteObjects(arg0 context.Context, arg1 *s3.DeleteObjectsInput, arg2 ...func(*s3.Options)) (*s3.DeleteObjectsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObjects", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *DeleterMockRecorder) DeleteObjects(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*Deleter)(nil).DeleteObjects), varargs...)
}
