// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomelo-la/go-toolkit/service/aws/s3 (interfaces: DownloadUploader)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/download_upload.go -package mock -mock_names DownloadUploader=DownloadUploader . DownloadUploader
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// DownloadUploader is a mock of DownloadUploader interface.
type DownloadUploader struct {
	ctrl     *gomock.Controller
	recorder *DownloadUploaderMockRecorder
}

// DownloadUploaderMockRecorder is the mock recorder for DownloadUploader.
type DownloadUploaderMockRecorder struct {
	mock *DownloadUploader
}

// NewDownloadUploader creates a new mock instance.
func NewDownloadUploader(ctrl *gomock.Controller) *DownloadUploader {
	mock := &DownloadUploader{ctrl: ctrl}
	mock.recorder = &DownloadUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DownloadUploader) EXPECT() *DownloadUploaderMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *DownloadUploader) GetObject(arg0 context.Context, arg1 *s3.GetObjectInput, arg2 ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *DownloadUploaderMockRecorder) GetObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*DownloadUploader)(nil).GetObject), varargs...)
}

// PutObject mocks base method.
func (m *DownloadUploader) PutObject(arg0 context.Context, arg1 *s3.PutObjectInput, arg2 ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *DownloadUploaderMockRecorder) PutObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*DownloadUploader)(nil).PutObject), varargs...)
}
