// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomelo-la/go-toolkit/service/aws/s3 (interfaces: Downloader)
//
// Generated by this command:
//
//	mockgen -destination ./mocks/downloader.go -package mock -mock_names Downloader=Downloader . Downloader
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// Downloader is a mock of Downloader interface.
type Downloader struct {
	ctrl     *gomock.Controller
	recorder *DownloaderMockRecorder
}

// DownloaderMockRecorder is the mock recorder for Downloader.
type DownloaderMockRecorder struct {
	mock *Downloader
}

// NewDownloader creates a new mock instance.
func NewDownloader(ctrl *gomock.Controller) *Downloader {
	mock := &Downloader{ctrl: ctrl}
	mock.recorder = &DownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Downloader) EXPECT() *DownloaderMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *Downloader) GetObject(arg0 context.Context, arg1 *s3.GetObjectInput, arg2 ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *DownloaderMockRecorder) GetObject(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*Downloader)(nil).GetObject), varargs...)
}
